ALTER TABLE  `site_playlists` ADD  `site_category_id` INT NOT NULL;

UPDATE  `site_playlists` SET  `site_category_id` =  '1' WHERE  `site_playlists`.`site_playlist_id` ='1' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '15' WHERE  `site_playlists`.`site_playlist_id` ='2' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '4' WHERE  `site_playlists`.`site_playlist_id` ='4' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '6' WHERE  `site_playlists`.`site_playlist_id` ='5' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '6' WHERE  `site_playlists`.`site_playlist_id` ='6' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '6' WHERE  `site_playlists`.`site_playlist_id` ='7' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '7' WHERE  `site_playlists`.`site_playlist_id` ='8' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '9' WHERE  `site_playlists`.`site_playlist_id` ='9' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '15' WHERE  `site_playlists`.`site_playlist_id` ='11' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '18' WHERE  `site_playlists`.`site_playlist_id` ='12' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '18' WHERE  `site_playlists`.`site_playlist_id` ='13' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '5' WHERE  `site_playlists`.`site_playlist_id` ='15' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '1' WHERE  `site_playlists`.`site_playlist_id` ='16' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '2' WHERE  `site_playlists`.`site_playlist_id` ='19' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '16' WHERE  `site_playlists`.`site_playlist_id` ='20' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '3' WHERE  `site_playlists`.`site_playlist_id` ='22' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '3' WHERE  `site_playlists`.`site_playlist_id` ='25' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '22' WHERE  `site_playlists`.`site_playlist_id` ='26' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '6' WHERE  `site_playlists`.`site_playlist_id` ='27' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '6' WHERE  `site_playlists`.`site_playlist_id` ='28' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '8' WHERE  `site_playlists`.`site_playlist_id` ='29' ;
UPDATE  `site_playlists` SET  `site_category_id` =  '24' WHERE  `site_playlists`.`site_playlist_id` ='30'; 